services:
  eve-route-builder:
    image: dansylvest/eve-route-builder:main
    container_name: eve-route-builder
    restart: always
    environment:
      - PORT=2001

  wanderer_db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  wanderer:
    image: wandererltd/community-edition:latest
    restart: always
    command: sh -c "sleep 10 && /app/entrypoint.sh db createdb && /app/entrypoint.sh db migrate && /app/entrypoint.sh run"
    depends_on:
      - eve-route-builder
      - wanderer_db
    healthcheck:
      disable: true
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@wanderer_db:5432/postgres
      - CUSTOM_ROUTE_BASE_URL=http://eve-route-builder:2001
      - PHX_SERVER=true
      - ECTO_IPV6=false
    env_file:
      - wanderer-conf.env.local

volumes:
  db-data:
    driver: local
